{
  flake.nixosModules.pkgs = { pkgs, ...}:
  {
    environment.systemPackages = with pkgs; [
      en
      fenix.complete.toolchain
      uv
      vim
      protonup-qt
      aseprite
        neovim
        libinput
        pgadmin4-desktopmode
        nix-output-monitor
        nvd
        gcc
        nh
        neofetch
        yazi
        btop
        udiskie
        p7zip
        unzip
        mesa
        nushell
        lightdm
        brightnessctl
        gtk2
        vlc
        unstable.discord
        tcpdump
        fzf
        pipes
        bat
        fish
        networkmanagerapplet
        xdg-desktop-portal
        xdg-desktop-portal-hyprland
        pkg-config
        openssl
        openssl.dev
        ntfs3g
        auto-cpufreq
        ripgrep
        impala
        nix-melt
        nix-tree
        tree
        eza
        zoxide
        dust
        unstable.xwayland-satellite
        linux-wifi-hotspot
        devenv
        heroic
        nil
        nix-init
        obs-studio

        ffmpeg_6
        miktex
        pango


        localsend
        jocalsend
        ];
 };
}
