[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

[templates.base16]
input_path = "~/.config/noctalia/templates/base16.json"
output_path = "/etc/nixos/nonNix/base16.json"

[templates.nvim-base16]
input_path = "~/.config/noctalia/templates/nvim-base16.lua"
output_path = "~/.config/nvim/lua/config/base16.lua"
post_hook = 'pkill -SIGUSR1 nvim'

# [templates.starship]
# input_path = "~/.config/noctalia/templates/starship.nix"
# output_path = "/etc/nixos/modules/terminal/starship.nix"

