[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

[templates.base16]
input_path = "~/.config/noctalia/templates/base16.json"
output_path = "/etc/nixos/nonNix/base16.json"
