[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/nix/store/h9zhp7hq5y8rkj3scxd9ygddz5p8arrz-noctalia-shell-2026-04-13_e56a9db/share/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/es46/.cache/noctalia/placeholder.json"

