{ pkgs, ...}:
{
  environment.systemPackages = with pkgs; [
  #  # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
  #  wget
     vim
     neovim
     hyprland
     xwayland
     libinput
     rustup
     pgadmin4-desktopmode
     nix-output-monitor
     nvd
     gcc
     nh
     neofetch
     yazi
     btop
     udiskie
     p7zip
     unzip
     tofi
     hyprpaper
     swaynotificationcenter
     nautilus
     blueman
     nushell
     fuzzel
     nwg-look
     lightdm
     brightnessctl
     gtk4
     gtk3    
     gtk2
     vlc
     discord
     tcpdump
     fzf
     pipes
     bat
     fish
     networkmanagerapplet
     xdg-desktop-portal
     pkg-config
     openssl
     openssl.dev
     ntfs3g
     auto-cpufreq
     rsync
     obsidian
  ];
}
